# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dynamic_cfg',
                'doc_host': 'https://enzokro.github.io',
                'git_url': 'https://github.com/enzokro/dynamic_cfg',
                'lib_path': 'dynamic_cfg'},
  'syms': {'dynamic_cfg.core': {'dynamic_cfg.core.foo': ('core.html#foo', 'dynamic_cfg/core.py')}}}
