# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_guidance.ipynb.

# %% auto 0
__all__ = ['DynamicCFG']

# %% ../nbs/01_guidance.ipynb 2
from .kdiff import *
from .schedules import name2schedule
from .normalizers import name2norm

# %% ../nbs/01_guidance.ipynb 3
class DynamicCFG:
    def __init__(self, norm_name='no_norm', schedule_name='constant'):
        self.normalizer = name2norm[norm_name]()
        self.scheduler = name2schedule[schedule_name]()


    def guide(self, uncond, cond, ts):
        """Applies dynamic Classifier-free Guidance.
        """
        # set the conditional and unconditional vectors
        self.normalizer.set_latents(u=uncond, t=cond)
        # compute the guidance update vector: (cond - uncond)
        self.normalizer.compute_update()

        # apply optional pre-processing
        self.normalizer.pre_process()

        # get the current, scheduled guidance scale 
        guidance_scale = self.scheduler.value_at(idx=ts)
        # run classifier-free guidance 
        self.normalizer.apply_cfg(guidance_scale)

        # apply optional post-processing
        self.normalizer.post_process()

        # return the dynamic noise prediction
        return self.normalizer.get_pred()


    def update_sched_kwargs(self, other_kwargs):
        self.scheduler.update_sched_kwargs(other_kwargs)


    def set_timesteps(self, num_steps):
        self.scheduler.set_num_steps(num_steps)
        self.scheduler.set_guidance_schedule()
